# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('marketplace', models.CharField(max_length=30)),
                ('order_purchase_date', models.DateTimeField()),
                ('order_amout', models.FloatField()),
                ('order_commission', models.FloatField()),
            ],
        ),
    ]
