# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_amout',
            new_name='order_amount',
        ),
    ]
